spring:
  jpa:
    database: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/db_cms?useUnicode=true&character=UTF8&autoReconnect=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
